= Spring Boot image:https://ci.spring.io/api/v1/teams/spring-boot/pipelines/spring-boot-2.4.x/jobs/build/badge["Build Status", link="https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.4.x?groups=Build"] image:https://badges.gitter.im/Join Chat.svg["Chat",link="https://gitter.im/spring-projects/spring-boot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
:docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference
:github: https://github.com/spring-projects/spring-boot

Spring Boot helps you to create Spring-powered, production-grade applications and
services with absolute minimum fuss. It takes an opinionated view of the Spring platform
so that new and existing users can quickly get to the bits they need.

通过springboot，你可以构建一个独立的、可以`java -jar`启动的java应用，或者war包。同时也提供了命令行工具来运行spring脚本

我们主要的目标是：

* 为所有spring开发者提供更快、更广泛的开发体验
* 方便的开箱即用，但是可以很方便的覆盖默认配置
* 提供给大型项目非功能性，通用的特性，(如：embedded servers, security, metrics, health checks, externalized configuration)
* 完全不需要代码生成和xml配置


== Getting help
Having trouble with Spring Boot? We'd like to help!

* Check the {docs}/html/[reference documentation], especially the
  {docs}/html/howto.html#howto[How-to's] -- they provide solutions to the most common
  questions.
* Learn the Spring basics -- Spring Boot builds on many other Spring projects, check
  the https://spring.io[spring.io] web-site for a wealth of reference documentation. If
  you are just starting out with Spring, try one of the https://spring.io/guides[guides].
* If you are upgrading, read the {github}/wiki[release notes] for upgrade instructions and
  "new and noteworthy" features.
* Ask a question - we monitor https://stackoverflow.com[stackoverflow.com] for questions
  tagged with https://stackoverflow.com/tags/spring-boot[`spring-boot`]. You can also chat
  with the community on https://gitter.im/spring-projects/spring-boot[Gitter].
* Report bugs with Spring Boot at {github}/issues[github.com/spring-projects/spring-boot/issues].



== Building from Source
You don't need to build from source to use Spring Boot (binaries in
https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and
greatest, Spring Boot can be built and published to your local Maven cache using the
https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper]. You also
need JDK 1.8.

[indent=0]
----
	$ ./gradlew publishToMavenLocal
----

This will build all of the jars and documentation and publish them to your local
Maven cache. It won't run any of the tests. If you want to build everything, use the
`build` task:

[indent=0]
----
	$ ./gradlew build
----

_Also see link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] if you wish to submit pull requests,
and in particular please fill out the
https://support.springsource.com/spring_committer_signup[Contributor's Agreement]
before your first change, however trivial._



== Modules
下面预览下spring boot的几个重要模块

=== spring-boot
为spring boot其他部分提供支撑的主要依赖，包括：

* SpringApplication提供静态的run方法用来创建一个独立的spring应用，它唯一的工作就是创建和刷新一个Spring `ApplicationContext`
* 嵌入式的web容器 (Tomcat, Jetty or Undertow)
* 一流的外部配置支持
* 方便的 `ApplicationContext` 初始化, 包括默认的智能日志记录


=== spring-boot-autoconfigure
Spring Boot只需要添加@EnableAutoConfiguration就可以自动配置大量的第三方配置，你只需添加依赖即可

自动配置会推断用户需要哪些bean。例如如果classpath里有HSQLDB的依赖，而且用户没有任何数据库连接的配置，
Spring Boot就会定义一个内存数据库。用户可以覆盖默认配置


=== spring-boot-starters
Starters是一组方便的依赖声明，你将获得一站式的服务，不再需要繁琐的配置和依赖声明。
例如只需要添加`spring-boot-starter-data-jpa`依赖就可以使用Spring and JPA for database。

=== spring-boot-cli
Spring command line application可以编译并运行Groovy源码，允许您编写最少的代码来让应用程序运行。
Spring CLI 还可以观察文件，当文件发生变化时，自动重新编译和重启。


=== spring-boot-actuator
Actuator endpoints使你可以监控你的应用并与之交互
Spring Boot Actuator提供了actuator endpoints需要的基础依赖，包括注解支持，开箱即用，提供了不限于
`HealthEndpoint`, `EnvironmentEndpoint`, `BeansEndpoint`等endpoints的暴露


=== spring-boot-actuator-autoconfigure
This provides auto-configuration for actuator endpoints based on the content of the classpath and a set of properties.
For instance, if Micrometer is on the classpath, it will auto-configure the `MetricsEndpoint`.
It contains configuration to expose endpoints over HTTP or JMX.
Just like Spring Boot AutoConfigure, this will back away as the user starts to define their own beans.


=== spring-boot-test
这个模块包含了应用测试所需的条目和注解


=== spring-boot-test-autoconfigure
像其他自动配置模块一样，spring-boot-test-autoconfigure提供了测试所需的自动配置。


=== spring-boot-loader
Spring Boot Loader提供了一个小魔法，使得可以构建一个通过`java -jar`运行的fat jar。
一般不需要单独引入Spring Boot Loader，只需添加spring-boot-maven-plugin插件即可


=== spring-boot-devtools
spring-boot-devtools模块提供了对应用开发时的协助，如自动重启，使得开发过程更顺滑。在运行一个fully packaged application时禁用



== Guides
The https://spring.io/[spring.io] site contains several guides that show how to use Spring
Boot step-by-step:

* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot] is a
  very basic guide that shows you how to create an application, run it and add some
  management services.
* https://spring.io/guides/gs/actuator-service/[Building a RESTful Web Service with Spring
  Boot Actuator] is a guide to creating a REST web service and also shows how the server
  can be configured.
* https://spring.io/guides/gs/convert-jar-to-war/[Converting a Spring Boot JAR Application
  to a WAR] shows you how to run applications in a web server as a WAR file.
